### ISSUE TITLE
Please add 'About' text to repo details

### ISSUE THREAD

**Issue by john-aws** [awslabs/aws-lc#110]
If you visit https://github.com/awslabs, most repos include an About summary that makes it simple to see, at a glance, what the repo is all about. This project does not contain About text.

![about-github](https://user-images.githubusercontent.com/3178883/110708373-96e58a80-81c8-11eb-9c50-3311dd8bde8b.png)

**Comment by bryce-shang** [comment]
Updated. Let me know if you have additional comments.

**Comment by bryce-shang** [comment]
Closed.
