### ISSUE TITLE
make fail with warnings

### ISSUE THREAD

**Issue by gbacskai** [awslabs/aws-lc#124]
### Problem:

pi@raspberrypi:~/aws-lc/build $ make
[  0%] Built target boringssl_gtest
[  1%] Built target crypto_test_data
[  1%] Built target global_target
[  2%] Built target test_support_lib
[  7%] Built target fipsmodule
[ 62%] Built target crypto
[ 63%] Built target urandom_test
[ 63%] Built target boringssl_gtest_main
[ 63%] Building CXX object crypto/CMakeFiles/crypto_test.dir/cipher_extra/aead_test.cc.o
/home/pi/aws-lc/crypto/cipher_extra/aead_test.cc: In member function ‘virtual void PerAEADTest_UnalignedInput_Test::TestBody()’:
/home/pi/aws-lc/crypto/cipher_extra/aead_test.cc:622:54: error: requested alignment 16 is larger than 8 [-Werror=attributes]
   alignas(16) uint8_t key[EVP_AEAD_MAX_KEY_LENGTH + 1];
                                                      ^
/home/pi/aws-lc/crypto/cipher_extra/aead_test.cc:623:58: error: requested alignment 16 is larger than 8 [-Werror=attributes]
   alignas(16) uint8_t nonce[EVP_AEAD_MAX_NONCE_LENGTH + 1];
                                                          ^
/home/pi/aws-lc/crypto/cipher_extra/aead_test.cc:624:39: error: requested alignment 16 is larger than 8 [-Werror=attributes]
   alignas(16) uint8_t plaintext[32 + 1];
                                       ^
/home/pi/aws-lc/crypto/cipher_extra/aead_test.cc:625:32: error: requested alignment 16 is larger than 8 [-Werror=attributes]
   alignas(16) uint8_t ad[32 + 1];
                                ^
/home/pi/aws-lc/crypto/cipher_extra/aead_test.cc:644:75: error: requested alignment 16 is larger than 8 [-Werror=attributes]
   alignas(16) uint8_t ciphertext[sizeof(plaintext) + EVP_AEAD_MAX_OVERHEAD];
                                                                           ^
/home/pi/aws-lc/crypto/cipher_extra/aead_test.cc:652:45: error: requested alignment 16 is larger than 8 [-Werror=attributes]
   alignas(16) uint8_t out[sizeof(ciphertext)];
                                             ^
cc1plus: all warnings being treated as errors
make[2]: *** [crypto/CMakeFiles/crypto_test.dir/build.make:167: crypto/CMakeFiles/crypto_test.dir/cipher_extra/aead_test.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:456: crypto/CMakeFiles/crypto_test.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

#### Relevant details
CPU architecture: Linux raspberrypi 5.10.17+ #1403 Mon Feb 22 11:26:13 GMT 2021 armv6l GNU/Linux
CPU name: (Xeon Platinum 8000, AMD EPYC 7000...)
OS: raspberry pi light 
Compiler: cmake version 3.16.3
AWS-LC commit: 7095a4b

**Comment by andrew-kaufman** [comment]
What compiler and version is being used when encountering this issue?

**Comment by gbacskai** [comment]
it is on the bottom of the comment:

Relevant details
CPU architecture: Linux raspberrypi 5.10.17+ #1403 Mon Feb 22 11:26:13 GMT 2021 armv6l GNU/Linux
CPU name: (Xeon Platinum 8000, AMD EPYC 7000...)
OS: raspberry pi light
Compiler: cmake version 3.16.3
AWS-LC commit: 7095a4b

**Comment by andrew-kaufman** [comment]
I did see those details that were provided, but for compiler it would also be helpful to know what version of GCC/Clang are being used in addition to the version of CMake. 

I also asked for the output of `uname -m`, because that helps us better understand what the architecture is being represented as for `CMAKE_SYSTEM_PROCESSOR`.

**Comment by gbacskai** [comment]
uname -m
armv7l

gcc --version
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cc --version
cc (Raspbian 8.3.0-6+rpi1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

c++ --version
c++ (Raspbian 8.3.0-6+rpi1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by dkostic** [comment]
This has already been an issue once, for example this commit https://github.com/awslabs/aws-lc/commit/c58a85f8ca4435a15798c037f18af1f55a23caa8 changed the alignment size from 64 to 16 because on aarch64 the compiler was giving the same warning/error. Here the compiler is complaining even about alignment of 16 because armv7l is a 32-bit architecture.

**Comment by dkostic** [comment]
Hello, so it seems that the issue you are seeing with the build on 32-bit ARM is related to a bug in `gcc` compiler (versions 7.2.1, 7.3, 8.2, 8.3.1, 9.2.1). Using `clang` compiler for example should solve the issue and you should be able to build the library. You can choose the compiler for cmake by prepending `CC=clang CXX=clang++` to the `cmake` invocation. Thanks for exploring the library and please let us know if this solves your problem!

**Comment by dkostic** [comment]
Thanks for reaching out to us! We are going to close this issue, let us know if trying a different compiler doesn't fix the issue and feel free to reopen the issue.
