### ISSUE TITLE
QUIC support

### ISSUE THREAD

**Issue by rock59** [awslabs/aws-lc#776]
I am planning to add aws-lc support to ngtcp2. Does aws-lc support quic ?

**Comment by torben-hansen** [comment]
Could you please elaborate on what you mean by "supporting Quic"?

We don't implement the Quic protocol.

**Comment by rock59** [comment]
@torben-hansen  Thanks for response. I found that Aws-lc is based on Boringssl and Boringssl supports all methods needed for Quic. I dont mean Quic protocol itself but all crypto and interaction methods that Quic needs. I am developing an IoT server that uses S2n-tls and I am planing to add Quic support too. As S2n-tls uses Aws-lc , I prefer to use Aws-lc Quic related methods in Ngtcp2 Quic stack too (not s2n-tls quic related methods or other TLS stacks).

**Comment by torben-hansen** [comment]
Hi there, please feel free to use any API we have.

Let us know if you can make an integration work!

**Comment by dkostic** [comment]
Closing the issue. Please let us know if you have any additional questions!
